name: Release LS version of webhook

on:
  workflow_dispatch:
    inputs:
      goVersion:
        description: 'Go version to build with'
        required: true
        type: string
        default: '1.24.9'
      tag:
        description: 'Tag to push'
        required: true
        type: string
jobs:
  build:
    # this is to prevent the job to run at forked projects
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_PUSH_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - name: Build container and push to Dockerhub registry
        env:
          TAG: ${{ inputs.tag }}
          GO_VERSION: ${{ inputs.goVersion }}
        run: |
          REPO=localstack/amazon-eks-pod-identity-webhook
          docker buildx build \
                -t $REPO:$TAG \
                --build-arg golang_image=public.ecr.aws/eks-distro-build-tooling/golang:${{ env.GO_VERSION }}-gcc \
                --platform=linux/amd64,linux/arm64 \
                --progress plain \
                --push .

